name: "Project Main Pipeline"

# 부모의 배포 버튼 클릭 -> 동시 배포
# 자식의 배포 버튼 클릭 -> 개별 배포

on:
  push:
    branches: [main]
    paths:
      - "terraform-Azure/**"
      - "terraform-AWS/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  call-azure:
    uses: .github/workflows/test.deploy.azure.yml
    secrets: inherit

  call-aws:
    uses: .github/workflows/test.deploy.aws.yml
    secrets: inherit